name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwayland-dev libxkbcommon-dev xorg-dev libglew-dev gcc-14 g++14
          version: 1.00
      - name: Set Defualt GCC
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/local/gcc-2.0/bin/g++14.2.0-4 100
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/local/gcc-2.0/bin/gcc14.2.0-4 100

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4

  windows-build:
    runs-on: windows-latest
    steps:
      - name: MSVC Setup
        uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
