name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglfw3 libglfw3 libglew-dev extra-cmake-modules
          version: 1.0

      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
